#!/bin/sh
pkill sxhkd
pkill feh
pkill polybar

# Compositor
pkill -x picom
picom --backend glx --daemon &

# 2. Start hotkey daemon
sxhkd &

# 3. Set wallpaper
feh --bg-fill ~/dotfiles/wallpapers/kaijun8.jpg &
setxkbmap -layout us,ru -option grp:alt_shift_toggle &

# 4. Start polybar
~/.config/polybar/launch.sh &

# 5. BSPWM Setup
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         2
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config top_padding 35
