wallpaper {
    monitor = DP-1
    path = /home/mihai/dotfiles/wallpapers/kaijun8.jpg
    fit_mode = cover
}
wallpaper {
    monitor =
    path = /home/mihai/dotfiles/wallpapers/kaijun8.jpg 
    fit_mode = cover
}
splash = false
ipc = off
