[colors]
background = #1e1e2e
foreground = #cdd6f4
primary = #f5c2e7
secondary = #89b4fa
alert = #f38ba8
disabled = #707880

[bar/mybar]
# Width 99% means 0.5% gap on each side (half of 98%)
width = 99%
height = 24pt

# Half the distance from the top (5 instead of 10)
offset-y = 5pt
# Centers the 99% width bar
offset-x = 0.5%

# Keeps the rounded "pill" look
radius = 12

# Keeps it floating
override-redirect = true
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt
padding-left = 2
padding-right = 2
module-margin = 1

font-0 = "monospace:size=10;2"
font-1 = "monospace:size=13;3"

modules-left = bspwm
modules-center = date
modules-right = tray memory pulseaudio wlan eth

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[module/bspwm]
type = internal/bspwm

# Use icons instead of index numbers
# You can change these icons to whatever you like
ws-icon-0 = 1;
ws-icon-1 = 2;󰈹
ws-icon-2 = 3;
ws-icon-3 = 4;󰺵
ws-icon-4 = 5;
ws-icon-default = 

# Label for the workspace currently being viewed
label-focused = %icon%
label-focused-background = #313244
label-focused-underline = ${colors.primary}
label-focused-padding = 2
label-focused-foreground = ${colors.primary}

# Label for workspaces that have windows open
label-occupied = %icon%
label-occupied-padding = 2
label-occupied-foreground = ${colors.secondary}

# Label for workspaces with urgent hints (notifications)
label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

# Label for empty workspaces
label-empty = %icon%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2

[module/date]
type = internal/date
interval = 1
date = "%{T2}%H:%M:%S%{T-} | %A %d %B"
label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/tray]
type = internal/tray
tray-padding = 1
tray-size = 16pt

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used%%

[module/pulseaudio]
type = internal/pulseaudio

# Left click opens pavucontrol
click-right = pavucontrol

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>
label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/eth]
type = internal/network
interface = enp4s0
interval = 3.0
format-connected-prefix = "ETH "
format-connected-prefix-foreground = ${colors.primary}
label-connected = %local_ip%

[module/wlan]
type = internal/network
interface = wlan0
interval = 3.0
format-connected-prefix = "WIFI "
format-connected-prefix-foreground = ${colors.primary}
label-connected = %essid%
# This makes the module disappear when not in use
format-disconnected =
